<a href="https://colab.research.google.com/github/ArchithBilla/Python-Projects-/blob/main/supplychain_raw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bronze Layer**

In [1]:
import pandas as pd

**1) Load the orders_raw dataset and inspect the first few rows to confirm the data structure and contents.**

In [5]:
df_orders = pd.read_excel("supplychain_raw.xlsx", sheet_name="orders_raw")

Displaying head to inspect

In [6]:
df_orders.head()

,order_id_raw,order_dt_raw,cust_region_raw,sku_raw,qty_raw,unit_price_raw,supplier_raw,promise_ship_dt_raw,currency_raw,order_channel_raw,promo_code_raw,customer_id_raw
0,ORD-1000,2026.01.05,SOUTH,SKU-A499,1 pcs,$155.94,SUP10,20260107,usd,Marketplace,NaN,C00583
1,Ord-1001,20-Jan-26,west,a354,01,"93,99",SUP-002,25-01-2026,NaN,NaN,NaN,C00029
2,ORD1002,Jan 16 2026,west,D674,4,139.35$,SUP-007,21-01-2026,$,NaN,FREESHIP,C00288
3,ORD1003,01/20/26,US-West,E846,1 pcs,"243,48",SUP03,NaN,usd,Marketplace,NaN,C01339
4,Ord-1004,01/06/26,mid-west,C265,03,154.39$,SUP02,Jan 08 2026,usd,web,WINTER5,cust-1259

**2) Load the shipments_raw dataset and inspect the first few rows**

In [7]:
df_shipments = pd.read_excel("supplychain_raw.xlsx", sheet_name="shipments_raw")

displaying head to inspect

In [8]:
df_shipments.head()

,shipment_id_raw,order_id_raw,ship_dt_raw,carrier_raw,whse_raw,qty_shipped_raw,ship_cost_raw,delivery_status_raw,tracking_raw
0,s9001,ORD1000,Jan 22 2026,fx,LAX-1,01,NaN,InTransit,NaN
1,S-9002,ORD1002,2026.01.18,DHL,CHI1,1,NaN,deliv,NaN
2,s9003,ORD1003,2026/01/04,NaN,NJ1,one,009.60,deliv,TRKPKYKSTNECW
3,S-9004,ord-1004,2026.01.13,DHL,NaN,4,10.32$,NaN,TRKV3NRO003MM
4,s9005,ord-1005,01/11/26,usps,LAX1,3 pcs,$17.53,Delayed,NaN

**3) Load the product_master_raw dataset and inspect the first few rows**

In [9]:
df_product = pd.read_excel("supplychain_raw.xlsx", sheet_name="product_master_raw")

Displaying head to inspect

In [10]:
df_product.head()

,sku_raw,category_raw,brand_raw,uom_raw,std_cost_raw,list_price_raw,supplier_raw,discontinued_raw
0,F214,Grocery,UrbanLeaf,EA,"151,90","102,34",SUP-002,N
1,A859,Sports,BrightWare,each,151.223,$200.34,SUP07,N
2,C350,Beauty,UrbanLeaf,PCS,85.43$,"41,73",SUP02,N
3,b242,Sports,BrightWare,PCS,USD 76,USD 61,SUP04,N
4,sku-f204,Sports,ZenithCo,each,"50,67",181.95$,sup-07,N

installing ydata profiling to generate a ProfileReport

In [18]:
pip install ydata_profiling

Collecting ydata_profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata_profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata_profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata_profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (4.4.4)
Collecting imagehash==4.3.2 (from ydata_profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (1.9.5)
Collecting dacite<2,>=1.9 (from ydata_profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata_profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata_profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata_profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 8.3 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 25.7 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 58.1 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 37.7 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 8.4 MB/s eta 0:00:00
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.5 MB/s eta 0:00:00
Installing collected packages: puremagic, minify-html, filetype, multimethod, dacite, imagehash, visions, phik, ydata_profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 visions-0.8.1 ydata_profiling-4.18.1

importing ProfileReport

In [19]:
from ydata_profiling import ProfileReport

In [20]:
ProfileReport(df_shipments).to_file("shipments_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]
 11%|█         | 1/9 [00:00<00:02,  3.89it/s]
 33%|███▎      | 3/9 [00:00<00:00,  7.60it/s]
 56%|█████▌    | 5/9 [00:00<00:00,  8.95it/s]
 78%|███████▊  | 7/9 [00:00<00:00,  9.64it/s]
100%|██████████| 9/9 [00:00<00:00,  9.24it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

**4) Summarize the orders_raw DataFrame**
> Null count

> Null Percentage

> Data Types

> Unique Values

In [32]:
null_counts = df_shipments.isnull().sum()
null_pct = (null_counts / len(df_shipments)) * 100
data_types = df_shipments.dtypes
unique_counts = df_shipments.nunique()
null_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique count": unique_counts})
null_summary

                     null   null_pct Data Types  Unique count
shipment_id_raw         0   0.000000     object          8737
order_id_raw            0   0.000000     object          8128
ship_dt_raw            93   1.064439     object           176
carrier_raw          1074  12.292549     object             7
whse_raw             1094  12.521460     object             7
qty_shipped_raw        87   0.995765     object            17
ship_cost_raw        2265  25.924230     object          1785
delivery_status_raw  1222  13.986494     object             6
tracking_raw         2258  25.844111     object          6479

In [30]:
null_counts = df_orders.isnull().sum()
null_pct = null_counts / len(df_orders) * 100
data_types = df_orders.dtypes
unique_counts = df_orders.nunique()
null_count_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique count": unique_counts})
null_count_summary

                     null  null_pct Data Types  Unique count
order_id_raw            0    0.0000     object          8000
order_dt_raw            0    0.0000     object           160
cust_region_raw         0    0.0000     object             9
sku_raw                 0    0.0000     object          1217
qty_raw                86    1.0750     object            22
unit_price_raw         42    0.5250     object          6458
supplier_raw           77    0.9625     object            40
promise_ship_dt_raw   159    1.9875     object           192
currency_raw         1627   20.3375     object             4
order_channel_raw    1134   14.1750     object             6
promo_code_raw       5975   74.6875     object             4
customer_id_raw       411    5.1375     object          3039

**5) Summarize the shipments_raw DataFrame to review its columns, data types, and overall completeness.**

In [230]:
null_counts = df_shipments.isnull().sum()
null_pct = null_counts / len(df_shipments) * 100
data_types = df_shipments.dtypes
unique_counts = df_shipments.nunique()
null_ship_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique Count": unique_counts})
null_ship_summary

                     null   null_pct Data Types  Unique Count
shipment_id_raw         0   0.000000     object          8737
order_id_raw            0   0.000000     object          8128
ship_dt_raw            93   1.064439     object           176
carrier_raw          1074  12.292549     object             7
whse_raw             1094  12.521460     object             7
qty_shipped_raw        87   0.995765     object            17
ship_cost_raw        2265  25.924230     object          1785
delivery_status_raw  1222  13.986494     object             6
tracking_raw         2258  25.844111     object          6479

**6) Summarize the product_master_raw DataFrame to see all product fields and their data types, checking for completeness**

In [247]:
null_counts = df_product.isnull().sum()
null_pct = null_counts / len(df_product) * 100
data_types = df_product.dtypes
unique_counts = df_product.nunique()
null_ship_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique Count": unique_counts})
null_ship_summary

                  null  null_pct Data Types  Unique Count
sku_raw              0       0.0     object           248
category_raw         0       0.0     object             6
brand_raw            0       0.0     object             6
uom_raw              0       0.0     object             5
std_cost_raw         0       0.0     object           243
list_price_raw       1       0.4     object           245
supplier_raw         1       0.4     object            40
discontinued_raw     4       1.6     object             4

**7. Computing basic statistics for numeric columns on orders_raw for quantity and price**

In [244]:
orders_stats = df_orders[['qty_raw','unit_price_raw']]
orders_stats

      qty_raw  unit_price_raw
0         1.0          155.94
1         1.0         9399.00
2         4.0          139.35
3         1.0        24348.00
4         3.0          154.39
...       ...             ...
7995      5.0          167.46
7996      1.0          227.80
7997      3.0           81.18
7998      1.0          123.00
7999     10.0           76.72

[8000 rows x 2 columns]

# ERROR RE-*RUNNING* THE CELL??

In [243]:
orders_stats['unit_price_raw'] = (
    orders_stats['unit_price_raw']
    .str.replace('$', '')
    .str.replace(',', '')
    .str.replace('USD', '')
    .astype(float)

)

AttributeError: Can only use .str accessor with string values!

In [245]:
orders_stats.describe()

           qty_raw  unit_price_raw
count  7336.000000     7958.000000
mean      3.342830     2759.379046
std       2.553978     6167.931616
min      -1.000000        8.000000
25%       2.000000       86.709000
50%       3.000000      165.385000
75%       4.000000      244.380000
max      10.000000    25946.000000

In [246]:
df_orders['qty_raw'].describe()

count    7336.000000
mean        3.342830
std         2.553978
min        -1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
Name: qty_raw, dtype: float64

In [135]:
df_orders['unit_price_raw'].describe()

count     7958.000000
mean      2759.379046
std       6167.931616
min          8.000000
25%         86.709000
50%        165.385000
75%        244.380000
max      25946.000000
Name: unit_price_raw, dtype: float64

**8) Statistical summaries for numerical feilds in products_master_raw over numerical columns**

In [138]:
products_stats = df_product[['std_cost_raw', 'list_price_raw']]
products_stats

    std_cost_raw list_price_raw
0         151,90         102,34
1        151.223        $200.34
2         85.43$          41,73
3         USD 76         USD 61
4          50,67        181.95$
..           ...            ...
245        62,89        229.295
246      USD 148         USD 13
247       USD 22         175,87
248      $152.67         77.851
249       24.693        231.48$

[250 rows x 2 columns]

In [139]:
products_stats['std_cost_raw'] = (
    products_stats['std_cost_raw']
    .str.replace('$', '')
    .str.replace(',', '.')
    .str.replace('USD', '')
    .astype(float)
)

/tmp/ipython-input-1072866758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_stats['std_cost_raw'] = (

In [140]:
products_stats['list_price_raw'] = (
    products_stats['list_price_raw']
    .str.replace('$', '')
    .str.replace(',', '.')
    .str.replace('USD', '')
    .astype(float)
)

/tmp/ipython-input-2552790043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_stats['list_price_raw'] = (

In [141]:
products_stats.describe()

       std_cost_raw  list_price_raw
count    250.000000      249.000000
mean      87.198204      123.878486
std       50.411199       70.652268
min        4.590000        6.130000
25%       42.857500       61.000000
50%       84.895000      125.000000
75%      134.315000      181.410000
max      179.950000      249.234000

9) Identify which columns in orders_raw have missing values and how many, to assess data completeness for order records.

> focusing on critical ones like order_id, customer_id, product_id

In [144]:
orders_missing = df_orders[['order_id_raw', 'customer_id_raw', 'order_id_raw']]
orders_missing

     order_id_raw customer_id_raw order_id_raw
0        ORD-1000          C00583     ORD-1000
1        Ord-1001          C00029     Ord-1001
2        ORD1002           C00288     ORD1002
3        ORD1003           C01339     ORD1003
4        Ord-1004       cust-1259     Ord-1004
...           ...             ...          ...
7995     ORD8995           C00685     ORD8995
7996     Ord-8996          C00381     Ord-8996
7997     ORD-8997          C00486     ORD-8997
7998       o-8998          C01697       o-8998
7999     Ord-8999       cust-1734     Ord-8999

[8000 rows x 3 columns]

In [145]:
nulls_in_orders = orders_missing.isnull().sum()
nulls_pct = nulls_in_orders / len(orders_missing) * 100
df_missing = pd.DataFrame({'null': nulls_in_orders, 'null_pct': nulls_pct})
df_missing

                 null  null_pct
order_id_raw        0    0.0000
customer_id_raw   411    5.1375
order_id_raw        0    0.0000

In [169]:
orders_missing[orders_missing['customer_id_raw'].isna()]

     order_id_raw customer_id_raw order_id_raw
13       ORD-1013             NaN     ORD-1013
23       ORD-1023             NaN     ORD-1023
98         o-1098             NaN       o-1098
101      ORD-1101             NaN     ORD-1101
108        o-1108             NaN       o-1108
...           ...             ...          ...
7929     ORD 8929             NaN     ORD 8929
7931     ORD8931              NaN     ORD8931
7933       o-8933             NaN       o-8933
7950       o-8950             NaN       o-8950
7958     ord-8958             NaN     ord-8958

[411 rows x 3 columns]

**10) Identify missing values in shipments_raw and count them to determine if any shipping information is incomplete.**

> shipments_raw (e.g., shipment_date, carrier, other relevant fields)

In [198]:
missing_shipment_details = df_shipments[['ship_dt_raw', 'carrier_raw']]
missing_shipment_details

      ship_dt_raw carrier_raw
0     Jan 22 2026          fx
1      2026.01.18        DHL
2      2026/01/04         NaN
3      2026.01.13        DHL
4        01/11/26        usps
...           ...         ...
8732   24-01-2026        UP S
8733     20260110          fx
8734  Jan 15 2026         UPS
8735  Jan 03 2026          fx
8736    19-Jan-26         NaN

[8737 rows x 2 columns]

In [199]:
missing_shipment_details['ship_dt_raw'] = (
    missing_shipment_details['ship_dt_raw']
    .str.replace('/', '-')
    .str.replace('Jan', '02')
    .str.replace(' ', '-')
    .str.replace(',', '-')
    .str.replace('.', '-')
)

/tmp/ipython-input-628152831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['ship_dt_raw'] = (

In [200]:
missing_shipment_details['ship_dt_raw']

0       02-22-2026
1       2026-01-18
2       2026-01-04
3       2026-01-13
4         01-11-26
           ...
8732    24-01-2026
8733      20260110
8734    02-15-2026
8735    02-03-2026
8736      19-02-26
Name: ship_dt_raw, Length: 8737, dtype: object

In [209]:
missing_shipment_details['ship_dt_raw'] = pd.to_datetime(missing_shipment_details['ship_dt_raw'], format= "mixed")

/tmp/ipython-input-4002348276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['ship_dt_raw'] = pd.to_datetime(missing_shipment_details['ship_dt_raw'], format= "mixed")

In [216]:
missing_shipment_details['ship_dt_raw'].isna()

np.int64(93)

> Identified the missing [ship_dt_raw] dates rows

In [223]:
missing_shipment_details[missing_shipment_details['ship_dt_raw'].isna()]

     ship_dt_raw carrier_raw
194          NaT        USPS
200          NaT         NaN
211          NaT        DHL
283          NaT        UP S
318          NaT         UPS
...          ...         ...
8112         NaT        usps
8322         NaT        usps
8353         NaT        DHL
8606         NaT        usps
8651         NaT         NaN

[93 rows x 2 columns]

In [225]:
missing_shipment_details['carrier_raw'] = missing_shipment_details['carrier_raw'].fillna('Unknown')

/tmp/ipython-input-771470343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['carrier_raw'] = missing_shipment_details['carrier_raw'].fillna('Unknown')

In [226]:
missing_shipment_details['carrier_raw'] = (
    missing_shipment_details['carrier_raw']
    .str.replace(' ', '')
    .str.replace('fx', 'FEDEX')
    .str.replace('usps', 'USPS')
    .str.replace('ups', 'UPS')
    .str.replace('fedex', 'FEDEX')
    .astype(str)
)

/tmp/ipython-input-3435429000.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['carrier_raw'] = (

In [227]:
missing_shipment_details['carrier_raw']

0         FEDEX
1           DHL
2       Unknown
3           DHL
4          USPS
         ...
8732        UPS
8733      FEDEX
8734        UPS
8735      FEDEX
8736    Unknown
Name: carrier_raw, Length: 8737, dtype: object

> Identified nulls and handled nulls with replacing as unknown carrier

In [229]:
missing_shipment_details['carrier_raw'].isna().sum()

np.int64(0)